
package proyecto1;

import javax.swing.JOptionPane;

public class FrmPPTLS extends javax.swing.JFrame {

    int aleatorio;
    int piedra=1;
    int papel=2;
    int tijera=3;
    int spock=4;
    int lagarto=5;
    int ganadas=0;
    int perdidas=-0;
    int total=0;
    
    
    public FrmPPTLS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btmPIEDRA = new javax.swing.JButton();
        btmPAPEL = new javax.swing.JButton();
        btmTIJERA = new javax.swing.JButton();
        btmLAGARTO = new javax.swing.JButton();
        btmSPOCK = new javax.swing.JButton();
        btmREINICIAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btmPIEDRA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/piedra.jpg"))); // NOI18N
        btmPIEDRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmPIEDRAActionPerformed(evt);
            }
        });

        btmPAPEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/papel.jpg"))); // NOI18N
        btmPAPEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmPAPELActionPerformed(evt);
            }
        });

        btmTIJERA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tijera.jpg"))); // NOI18N
        btmTIJERA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmTIJERAActionPerformed(evt);
            }
        });

        btmLAGARTO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lagarto.jpg"))); // NOI18N
        btmLAGARTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmLAGARTOActionPerformed(evt);
            }
        });

        btmSPOCK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spock.jpg"))); // NOI18N
        btmSPOCK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmSPOCKActionPerformed(evt);
            }
        });

        btmREINICIAR.setText("Reiniciar");
        btmREINICIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmREINICIARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btmTIJERA)
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btmLAGARTO)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btmPAPEL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(btmSPOCK)))
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btmPIEDRA)
                        .addGap(221, 221, 221))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btmREINICIAR)
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btmPIEDRA)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btmSPOCK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(btmLAGARTO)
                        .addGap(16, 16, 16)
                        .addComponent(btmREINICIAR)
                        .addGap(84, 84, 84))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btmPAPEL)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btmTIJERA)
                .addGap(287, 287, 287))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmPIEDRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmPIEDRAActionPerformed
        total=total+1;
    if (aleatorio == tijera ) 
        { 
             JOptionPane.showMessageDialog(null,"  PIEDRA GANA TIJERA"
                     + " ¡VICTORIA! ");
             ganadas=ganadas+1;
        }
    else if(aleatorio== lagarto)
        {
             JOptionPane.showMessageDialog(null," PIEDRA GANA LAGARTO"
                     + " ¡VICTORIA! ");
             ganadas=ganadas+1;
        }
    else if(aleatorio == spock )
        {   
             JOptionPane.showMessageDialog(null," SPOCK GANA PIEDRA"
                     + " ¡PIERDES! ");
             perdidas=perdidas+1;
        }
    else if (aleatorio == papel )
        {
            JOptionPane.showMessageDialog(null," PAPEL GANA A PIEDRA "
                    + " ¡PIERDES! ");
            perdidas=perdidas+1;
        }
    else 
        {
            JOptionPane.showMessageDialog(null," ¡EMPATE!  "); 
        }
    }//GEN-LAST:event_btmPIEDRAActionPerformed

    private void btmPAPELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmPAPELActionPerformed
         total=total+1;
    if (aleatorio == spock ) 
        { 
             JOptionPane.showMessageDialog(null," PAPEL GANA SPOCK"
                     + " ¡VICTORIA! ");
             ganadas=ganadas+1;
        }
    else if(aleatorio== piedra)
        {
             JOptionPane.showMessageDialog(null," PAPEL GANA PIEDRA "
                     + " ¡VICTORIA! ");
             ganadas=ganadas+1;
        }
    else if(aleatorio == lagarto )
        {   
             JOptionPane.showMessageDialog(null, " LAGARTO GANA PAPEL "
                     + " ¡PIERDES!");
             perdidas=perdidas+1;
        }
    else if (aleatorio == tijera )
        {
            JOptionPane.showMessageDialog(null," TIJERA GANA A PAPEL "
                    + " ¡PIERDES!");
            perdidas=perdidas+1;
        }
    else 
        {
            JOptionPane.showMessageDialog(null," ¡EMPATE!  "); 
        }
    }//GEN-LAST:event_btmPAPELActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        aleatorio=(int)(Math.random()*5+1);
        System.out.print(aleatorio); 
    }//GEN-LAST:event_formWindowOpened

    private void btmTIJERAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmTIJERAActionPerformed
        total=total+1;
    if (aleatorio == lagarto) 
        { 
             JOptionPane.showMessageDialog(null,"  TIJERA GANA A LAGARTO"
                     + "¡ VICTORIA!");
             ganadas=ganadas+1;
             
        }
    else if(aleatorio==papel)
        {
             JOptionPane.showMessageDialog(null," TIJERA GANA PAPEL"
                     + " ¡VICTORIA! ");
             ganadas=ganadas+1;
        }
    else if(aleatorio == piedra)
        {   
             JOptionPane.showMessageDialog(null," PIEDRA GANA TIJERA"
                     + " ¡PIERDES! ");
             perdidas=perdidas+1;
        }
    else if(aleatorio == spock)
        {
             JOptionPane.showMessageDialog(null," SPOCK GANA TIJERA"
                     + " ¡PIERDES! "); 
             perdidas=perdidas+1;
        }
    else
        {
             JOptionPane.showMessageDialog(null," ¡EMPATE! ");
        }
    }//GEN-LAST:event_btmTIJERAActionPerformed

    private void btmSPOCKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmSPOCKActionPerformed
        total=total+1;
    if (aleatorio == piedra ) 
        { 
             JOptionPane.showMessageDialog(null," SPOCK GANA A PIEDRA "
                     + " ¡VICTORIA! ");
             ganadas=ganadas+1;
        }
    else if(aleatorio== tijera)
        {
             JOptionPane.showMessageDialog(null," SPOCK GANA A TIJERA "
                     + " ¡VICTORIA! ");
             ganadas=ganadas+1;
        }
    else if(aleatorio == lagarto )
        {   
             JOptionPane.showMessageDialog(null," LAGARTO GANA A SPOCK "
                     + " ¡PIERDES!");
             perdidas=perdidas+1;
             
        }
    else if (aleatorio == papel)
        {
            JOptionPane.showMessageDialog(null," PAPEL GANA A SPOCK "
                    + " ¡PIERDES! ");
            perdidas=perdidas+1;
        }
    else 
        {
            JOptionPane.showMessageDialog(null," ¡EMPATE!  "); 
        }
    }//GEN-LAST:event_btmSPOCKActionPerformed

    private void btmREINICIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmREINICIARActionPerformed
        aleatorio=(int)(Math.random()*5+1);
        System.out.print(aleatorio);
    }//GEN-LAST:event_btmREINICIARActionPerformed

    private void btmLAGARTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmLAGARTOActionPerformed
        total=total+1;
        if (aleatorio == spock ) 
        { 
             JOptionPane.showMessageDialog(null," LAGARTO GANA SPOCK "
                     + " ¡VICTORIA! ");
             ganadas=ganadas+1;
        }
        else if(aleatorio== papel)
        {
             JOptionPane.showMessageDialog(null," LAGARTO GANA PAPEL "
                     + " ¡VICTORIA! ");
             ganadas=ganadas+1;
        }
        else if(aleatorio == piedra )
        {   
             JOptionPane.showMessageDialog(null," PIEDRA GANA A LAGARTO "
                     + " ¡PIERDES! ");
             perdidas=perdidas+1;
        }
        else if (aleatorio == tijera )
        {
            JOptionPane.showMessageDialog(null," TIJERA GANA A LAGARTO "
                    + " ¡PIERDES! ");
            perdidas=perdidas+1;
        }
        else 
        {
            JOptionPane.showMessageDialog(null," ¡EMPATE!  "); 
        }
    }//GEN-LAST:event_btmLAGARTOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPPTLS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPPTLS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPPTLS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPPTLS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPPTLS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmLAGARTO;
    private javax.swing.JButton btmPAPEL;
    private javax.swing.JButton btmPIEDRA;
    private javax.swing.JButton btmREINICIAR;
    private javax.swing.JButton btmSPOCK;
    private javax.swing.JButton btmTIJERA;
    // End of variables declaration//GEN-END:variables
}
